remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme

title: My Blog
description: A minimal blog about thoughts and ideas.

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
